use_frameworks!

platform :ios, '10.0'

target 'iOSLoggingLibrary_Example' do
  pod 'iOSLoggingLibrary', :path => '../'

  target 'iOSLoggingLibrary_Tests' do
    inherit! :search_paths

    
  end
end
